---
title: Shrutika Dhake
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shrutikadhake.github.io/portfolio/"
repository: just-the-docs/just-the-docs # for github-metadata
theme: jekyll-theme-slate
